version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
      
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Unit Tests
          command: dotnet test src/Intercom.Tests/Intercom.Tests.csproj

      - run:
          name: Integ Tests
          command: dotnet test src/Intercom.Tests.Integration/Intercom.Tests.Integration.csproj